import os

# internal
INTERNAL_SSL_VERIFY = bool(int(os.getenv("RACCOON_INTERNAL_SSL_VERIFY", 0)))
INTERNAL_API_BASE_URL = os.getenv("RACCOON_INTERNAL_API_BASE_URL", "localhost:5284")

# redis
REDIS_HOST = os.getenv("RACCOON_REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("RACCOON_REDIS_PORT", 6379))
REDIS_DB = int(os.getenv("RACCOON_REDIS_DB", 0))
REDIS_TIME_SERIES_DUPLICATE_POLICY = os.getenv(
    "RACCOON_REDIS_TIME_SERIES_DUPLICATE_POLICY", "last"
)
REDIS_TIME_SERIES_RETENTION_SECONDS = int(
    os.getenv("RACCOON_REDIS_TIME_SERIES_RETENTION_SECONDS", 14400000)
)

# service
SERVICE_LOG_LEVEL = str.upper(os.getenv("RACCOON_WEBSOCKET_SERVICE_LOG_LEVEL", "info"))
SERVICE_STREAM_LIFETIME_SECONDS = int(
    os.getenv("RACCOON_WEBSOCKET_SERVICE_STREAM_LIFETIME_SECONDS", 86800)
)
SERVICE_LOCAL_DEVELOPMENT = bool(
    int(os.getenv("RACCOON_WEBSOCKET_SERVICE_LOCAL_DEVELOPMENT", 0))
)
